apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: gcp-service-account-credentials-volume
          secret:
            secretName: gcs-credentials-file
            items:
            - key: gcs-credentials.json
              path: gcs-credentials.json
      initContainers:
        - name: install-ksops
          # Match Argo CD Go version
          image: viaductoss/ksops:v2.1.2-go-1.14
          command: ["/bin/sh", "-c"]
          args:
            - echo "Installing KSOPS...";
              export PKG_NAME=ksops;
              mv ${PKG_NAME}.so /custom-tools/;
              mv $GOPATH/bin/kustomize /custom-tools/;
              echo "Done.";
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /usr/local/bin/kustomize
              name: custom-tools
              subPath: kustomize
              # Verify this matches a XDG_CONFIG_HOME=/.config env variable
            - mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops.so
              name: custom-tools
              subPath: ksops.so
            - mountPath: /etc/gcp
              name: gcp-service-account-credentials-volume
              readOnly: true
          env:
            - name: XDG_CONFIG_HOME
              value: /.config
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/gcs-credentials.json
